# Generated by Django 5.1.5 on 2025-02-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list_student',
            new_name='student',
        ),
    ]
